services:
  - type: web
    name: gestao-web
    env: python
    region: oregon
    plan: free
    
    buildCommand: >
      pip install -r requirements-web.txt
    
    startCommand: >
      gunicorn app:app --bind 0.0.0.0:10000
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
